set(_CATKIN_CURRENT_PACKAGE "camera_2d")
set(camera_2d_VERSION "0.0.0")
set(camera_2d_MAINTAINER "BioBot <biobotus@gmamil.com>")
set(camera_2d_PACKAGE_FORMAT "1")
set(camera_2d_BUILD_DEPENDS "rospy")
set(camera_2d_BUILD_EXPORT_DEPENDS "rospy")
set(camera_2d_BUILDTOOL_DEPENDS "catkin")
set(camera_2d_BUILDTOOL_EXPORT_DEPENDS )
set(camera_2d_EXEC_DEPENDS "rospy")
set(camera_2d_RUN_DEPENDS "rospy")
set(camera_2d_TEST_DEPENDS )
set(camera_2d_DOC_DEPENDS )
set(camera_2d_DEPRECATED "")